version: '3'
services:
  node:
    container_name: node-web
    restart: always
    build: .
    ports:
      - '8080:8080'
    links:
      - 'mongo'
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27517:27517'
